project:
  type: website
  output-dir: docs

website:
  title: "CSDisseminate"
  favicon: /Images/favicon-96x96.png
  #announcement: 
  #  icon: info-circle
  #  dismissable: true
  #  content: "Register today for CSDisseminate's Open Data Workshop on June 3rd, 2025! [Click here to learn more!](https://www.csdisseminate.com/Announcements/2025_05_02_Open-Data-Webinar/)"
  #  type: info
  #  position: below-navbar
  navbar:
    title: " 
  ![](/Images/CSDisseminate Logo_White Logo_Purple Background Circle.png){width=45}
  \\ \\
  CSDisseminate"
    right:
      - text: "Home"
        href: index.qmd
      - text: "People"
        menu:
          - text: "Meet the Team"
            href: team.qmd
          - text: "Join Us"
            href: join-us.qmd
          - text: "Featured Scientists"
            href: featured-scientists.qmd
      - text: "Research"
        href: Research/index.qmd
      - text: "Resources"
        href: resources.qmd
      - text: "Events"
        href: events.qmd
      #- text: "Resources"
      #  href: resources.qmd
      #- text: "Events"
      #  href: events.qmd
  back-to-top-navigation: true
  page-footer:
    left: 
      - icon: github
        href: https://github.com/
      - icon: instagram 
        href: https://www.instagram.com/csdisseminate
  
        
        
# Define a collection named "Posts"
collections:
  Posts:
    title: "Announcements"
    # The pattern must match the folder and file extension
    pattern: "Announcements/*.qmd"
    sort: "date desc"
  Team:
    title: "Team"
    pattern: "Team/*.qmd"
  FeaturedScientists:
    title: "Featured Scientists"
    pattern: "FeaturedScientists/*.qmd"
    sort: "date desc"

format:
  html:
    theme: cosmo
    css: /styles.css
    toc: true
    metadata:
      pagetitle: "CSDisseminate"
    include-after-body: custom-footer.html
    resources:
      - cards/custom-card.ejs

editor: visual

