project:
  type: website
  output-dir: docs

website:
  title: "CSDisseminate"
  favicon: /Images/favicon/favicon-96x96.png
  navbar:
    title: " 
  ![](/Images/CSDisseminate Logo_White Logo_Purple Background Circle.png){width=45}
  \\ \\
  CSDisseminate"
    right:
      - text: "Home"
        href: index.qmd
      - text: "People"
        href: team.qmd
        menu:
          - text: "Meet the Team"
            href: team.qmd
          - text: "Join Us"
            href: joinUs.qmd
          - text: "Featured Scientists"
            href: FeaturedScientists.qmd
      - text: "Research"
        href: research.qmd
      - text: "Resources"
        href: resources.qmd
      - text: "Events"
        href: events.qmd
  back-to-top-navigation: true
  page-footer:
    left: 
      - icon: github
        href: https://github.com/
      - icon: instagram 
        href: https://www.instagram.com/csdisseminate
  
        
        
# Define a collection named "Posts"
collections:
  Posts:
    title: "Announcements"
    # The pattern must match the folder and file extension
    pattern: "Announcements/*.qmd"
    sort: "date desc"
  Team:
    title: "Team"
    pattern: "Team/*.qmd"
  FeaturedScientists:
    title: "Featured Scientists"
    pattern: "FeaturedScientists/*.qmd"
    sort: "date desc"

format:
  html:
    theme: cosmo
    css: /styles.css
    toc: true
    metadata:
      pagetitle: "CSDisseminate"
    include-after-body: custom-footer.html
    resources:
      - cards/custom-card.ejs

editor: visual

