---
title: "Join Us"
---

## Interested in getting involved?

Join us as we expand our reach to all CSD scientists!

Check out the options listed below that best match your interests. Then, send us an email at CSDisseminate\@gmail.com or use the contact form below to let us know how you'd like to participate!

## Ambassadors

**Want to help your colleagues get started with self-archiving?**

Be a CSDisseminate Ambassador at your institution or among your social network of colleagues!

As the local go-to on self-archiving, you can help your colleagues provide free, legal research articles to other scientists, clinicians, and the general public. You can champion self-archiving at your institution or within your organization as a CSDisseminate Ambassador by first:

1.  Watching the Self-Archiving 101 workshop video (or attending a live Self-Archiving 101 workshop).

2.  Taking the self-assessment to see if there are any concepts you want to brush up on.

Then:

-   Starting to self-archive your own or your lab’s research.

    -   Earn a place as a featured scientist who self-archives on our site!

    -   Earn badges for self-archiving (coming soon)!

-   Presenting a Self-Archiving 101 workshop at your institution.

    -   Customize these slides & resources with information about your institution.

    -   Present anywhere you like! During a seminar, course, lab meeting, or department meeting.

-   Being available to answer questions from your colleagues about the steps of self-archiving.

    -   Use our Forum (coming soon) to crowdsource answers to difficult or complicated questions.

-   Sharing social media posts from CSDisseminate to relevant social media groups or platforms.

### Does my Institution need a CSDisseminate Ambassador? ​

Here are some ideas to help you better understand if/how self-archiving is currently being done at your institution or within your organization:

Review your institution’s lab web pages & see if/how they list their publications.

-   Are articles recently updated with a full citation?

-   Are articles linked to the doi?

-   Are self-archived, free versions of manuscripts linked?

-   Are they following appropriate guidelines re: which version is allowed to be posted?

Find out if your institution has a repository for articles. Talk to your institution’s library/research dept to get a handle on how the institutional repository works.

-   Who do you contact if you have an article to submit to the repository?

-   What versions of articles will they accept?

-   How quickly are articles posted after submitting to the repository?

-   Are you able to revise versions of articles submitted to the repository?

At most Universities, there’s quite a bit of variability in how much each lab or scientist participates in self-archiving. But having a point-person to discuss it with is helpful for pretty much everyone!

Thank you for considering being a self-archiving Ambassador. If interested, please contact csdisseminate\@gmail.com.

## Collaborators

**Are you a self-archiver who is interested in supporting the mission of CSDisseminate in more of a long-term role?**

​CSDisseminate collaborators actively participate in quarterly meetings.

Collaborators are expected to:

-   Provide input on direction and mission of CSDisseminate

-   Seek out new content to share with scientists and clinicians

-   Regularly/Semi-regularly participate and/or lead activities or events hosted by CSDisseminate

-   Support content development for CSDisseminate events, CSDisseminate website, social media

-   Be an Ambassador for self-archiving at your institution or within your organization.
